### ISSUE TITLE
Inheritance Instead of typedefs?

### ISSUE THREAD

**Issue by pbauman** [grinsfem/grins#341]
For things like `PhysicsName`, `PhysicsList`, etc. that are used beyond local scope convenience, I'm thinking that maybe inheritance could be better than typedef? Although we won't add anything, it will force it to pop up in Doxygen in the class index and make it much easier to find out what it actually is.

**Comment by roystgnr** [comment]
Changing the design in order to accomodate Doxygen sounds like an awful idea.  And there do seem to be Doxygen commands which let you explicitly decide where and how to document typedefs.

The only advantage I could see to inheritance or composition is that we could then use forward declarations and be able to more easily change things under the hood later.
