### ISSUE TITLE
Go Full C++11?

### ISSUE THREAD

**Issue by pbauman** [grinsfem/grins#416]
Given the discussion [here](https://github.com/libMesh/libmesh/issues/655), since the only thing holding back libMesh is Dakota's not-using-c++11-yet-but-uses-queso-which-can-use-libmesh, maybe it's a good time to switch?

**Comment by roystgnr** [comment]
:+1: from me.  I'd even support requiring C++14.  We should probably mandate whichever we support in the CI testing, though; otherwise I can just see myself slipping in C++17 (or C++14 if we decide to stick with 11) code and not noticing.  I'm pretty solid on remembering what is and isn't C++03 compatible but the latter standards and pre-standards blur together a bit.

**Comment by pbauman** [comment]
Awesome. I have no objection to requiring C++14 (in fact, I think we should mandate it for Antioch so we can remove all those macros, will open issue for discussion there), but would we use any of those features in GRINS? Granted, I'm not intimately familiar with all the new specs. 

For GCC, 4.8.2 was C++11 feature complete, so any RHEL 7 based system will natively support C++11. GCC 5 was C++14 complete. My experience has been that the supercomputing centers will deploy a GCC installation if requested, so it shouldn't be a problem.

Intel is more dubious. [C++11 Status](https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler) and [C++14 Status](https://software.intel.com/en-us/articles/c14-features-supported-by-intel-c-compiler). Looks like Intel 14+ supports all of the C++11 features we'd want to use and the C++14 auto/decltype feature we'd want in Antioch is in Intel 15. However, generic lambdas aren't around until Intel 16. Now, I don't even use Intel really anymore, but I'm not sure how constrained you are in terms of Intel usage.

**Comment by nicholasmalaya** [comment]
I'll vote (or perhaps more accurately,  advise) against going full c++14, because we are so likely to be using TACC machines and the GNU support has been spotty.  Typically we have PGI or Intel, so this could be a problem.

C++11 should be groovy, though. 

I would love to know where @roystgnr is getting references and experience with c++17, since Bjarne's book has not yet been updated. And that is my 'goto'.

**Comment by roystgnr** [comment]
IIRC I was reading something about what stuff made it into the final C++14 draft and what was still getting revisions?  I recall non-member size() looking interesting for some of the MetaPhysicL stuff, plus there was a crazy accident or two in the standard for which the fix didn't make it in yet:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4051.html

**Comment by pbauman** [comment]
We're now mandating C++11 as of #522.
